# Generated by Django 5.1.2 on 2024-10-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
    ]
