# Generated by Django 5.1.2 on 2024-12-17 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_task_time_spent_task_timer_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
